// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
Texture2D<float4> Mask;
float2 HitUV;
float1 Step;

float2 GetUV(uint3 id)
{
    return (id.xy + 0.5) * Step - 1.0;
}

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float2 IDUV = GetUV(id);
    if ((IDUV.x - HitUV.x) * (IDUV.x - HitUV.x) - (IDUV.y * HitUV.y) * (IDUV.y * HitUV.y) < (Step * Step))
        Result[id.xy] = float4(1, 1, 1, 1);
}
