// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
float2 HitUV;
uint2 HitXY;
uint2 Res;
float1 Step;

float2 GetUV(uint3 id)
{
    return (id.xy + 0.5f) * Step - 1.0f;
}

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    /*if (id.x == HitXY.x && id.y == HitXY.y)
    for (int i = -20; i < 20; i++)
    {
        for (int j = -20; j < 20; j++)
        {
                float idx = (HitXY.x + i)%Res.x;
                if (idx < 0) idx = Res.x - idx;
                float idy = (HitXY.y + j) % Res.y;
                if (idy < 0) idy = Res.y - idy;
                float2 nid = float2(idx, idy);
                Result[nid] = float4(1, 1, 1, 1);
        }

    }*/
    if (((HitXY.x - id.x) * (HitXY.x - id.x)) + ((HitXY.y - id.y) * (HitXY.y - id.y)) < 600)
        Result[id.xy] = float4(0, 0, 0, 0);
  
}
